print ("Welcome! Please give me 2 numbers!")
x = int(input ("Number 1: "))
y = int(input ("Number 2: "))

adding = str(x+y)
resting = str(x-y)
multiplying = str(x*y)
divide = str(x//y)
rest = str(x%y)

print ("The sum would be: " + adding)
print ("The rest would be: " + resting)
print ("The product would be: " + multiplying)
print ("The division would be: " + divide)
print ("The remainder would be: " + rest)